# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f19732c76e33bca4497576619c654c4cebd829ec60ffa7a18754e2a3446dfece89f525368f1f2a5987c91bd93053fb16491d18d040cc9696d6149ad7dbc7a41
  PUBLISHABLE_KEY: pk_test_jzECTDFq6RfuT8AidMVpRdBr
  SECRET_KEY: sk_test_zeBP7vaPVaRcOT424Dz9C8ET

test:
  secret_key_base: 135dfb2405356c415fb9fcd09483f9d6c28be0053388b47dcb5c87d890df671c1540f54decf78d162e06ed70c4c4a0d1790bb5428100c55afb932194591c12af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 0d6561fd4102a3319125761247a5b82d24233f365c15876ad490e1c89d9b0cd74bd1e3060d9e7334fb5970d29c7be800a021d635658dd0785b5e72a5aaaac0d1

